name: Backend CI
on:
  push:
    branches: [ main ] # Chạy khi bạn push code lên nhánh main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: echo "Kiểm tra code thành công, Render sẽ tự động deploy bản mới!"